### ISSUE TITLE
Add hero component

### ISSUE THREAD

**Issue by stand87** [fahenao/_cultural_portobelo#19]

**Comment by stand87** [comment]
Hey @fahenao tengo este componente que es el header del home, necesito que me avises especificamente que deseas promocionar aqui, un libro, parte del servicio, una descripcion de la actividad e la empresa, etc.

![screenshot 13](https://user-images.githubusercontent.com/16023423/28558321-f9c3689a-70d6-11e7-9f01-c028a901424f.png)

**Comment by fahenao** [comment]
Por ahora queremos promocionar los códigos de Editorial Portobelo y las
novedades como este libro:

https://www.facebook.com/commerce/products/1458277557544699/?hc_ref=ARQxWeQBnHvbB4ybCACAYtiwmeIyt0mgwkzhMpr_csED7yMvTaF81rjthE1NC3pk1LY


2017-07-25 1:17 GMT-05:00 Carlos Garcia <notifications@github.com>:
