### ISSUE TITLE
Refactor searchbar component

### ISSUE THREAD

**Issue by stand87** [fahenao/_cultural_portobelo#29]
## Problem
As a customer, I should be able to see results after submit an information un the searchbar, so I can find books

## Acceptance Criteria
- As a customer, I should be able to see to find books by introducing one of the next information:
  - Author
  - Title
  - Product code
  - Category

**Comment by stand87** [comment]
Hey @fahenao, andaba haciendo refactor de esto, tengo un par de preguntas acerca del proyecto del cotizador.

Esto es correcto? Vi que el view de resultados de busquedas cambia y que ahora es una tabla que te muestra resultados con acciones. Esto lo debe ver el usuario o el administrador?

![image](https://user-images.githubusercontent.com/16023423/29753391-1a65428e-8b36-11e7-83ad-663629139f12.png)

**Comment by fahenao** [comment]
Esto lo debe ver el admin unicamente.

**Comment by stand87** [comment]
Hey @fahenao revisa este error que me salta cuando trato de buscar un libro en la app de prueba https://whispering-dusk-95971.herokuapp.com/books?utf8=%E2%9C%93&search=Editorial+Portobelo

![image](https://user-images.githubusercontent.com/16023423/29857981-073e5fc8-8d21-11e7-8345-b15e09e0ee1b.png)

**Comment by fahenao** [comment]
Como puedo simular esto? hago pull de tu branch?

2017-08-30 1:18 GMT-05:00 Carlos Garcia <notifications@github.com>:
